version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    user: frontend_user
    command: npm run start
    ports:
      - 3000:3000
    env_file:
      - frontend.env
    environment:
      NEXT_TELEMETRY_DISABLED: 1
      NODE_ENV: production
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/etc/nginx/proxy_params:/etc/nginx/proxy_params:ro
      - ./certbot/var/www/certbot/:/var/www/certbot/:ro
      - ./certbot/etc/letsencrypt/:/etc/letsencrypt/:ro
    depends_on:
      - frontend
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/var/www/certbot/:/var/www/certbot/:rw
      - ./certbot/etc/letsencrypt/:/etc/letsencrypt/:rw
      - ./certbot/var/log/letsencrypt/:/var/log/letsencrypt/:rw
